export const projectsData = [
    {
        id: "1",
        name: "Tours de Kiev",
        title: "Touristic agency website",
        role: "Development",
        imgUrl: "/images/projects/tdk-screenshot.jpg",
        description: "Website of an active travel agency specializing in tours in Kyiv and Ukraine. More than 40 years in the market. Thousands of satisfied clients.",
        url: "https://toursdekiev.com.ua/",
        urlTitle: "toursdekiev.com.ua",
    },
    {
        id: "2",
        name: "Jugue tear",
        title: "Website about sharing adapted toys.",
        role: "Programing",
        imgUrl: "/images/projects/j-screenshot.jpg",
        description: `Website about adapting and providing toys for boys and girls with complex motor disabilities.`,
        url: "https://juguetear-web.vercel.app/",
        urlTitle: "juguetear.vercel.app",
    },
    {
        id: "3",
        name: "Disla Shop",
        title: "Wheels online shop",
        role: "Idea, PM, Support",
        imgUrl: "/images/projects/disla-screenshot.jpg",
        description: "Online shop of the first Ukraine lite alloy wheels manufacturer.",
        url: "https://dislashop.com/",
        urlTitle: "dislashop.com",
    },
]
